apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickbite-frontend
spec:
  selector:
    matchLabels:
      app: quickbite-frontend
  template:
    metadata:
      labels:
        app: quickbite-frontend
    spec:
      containers:
        - name: quickbite-frontend
          image: sabinghost19/quickbite-frontend:v9.0
          env:
            - name: API_BASE_URL
              value: "http://user-service"
            - name: RESTAURANTS_SERVICE_URL
              value: ""
            - name: ORDERS_SERVICE_URL
              value: "http://orders-service"
            - name: PAYMENTS_SERVICE_URL
              value: "http://payments-service"
            - name: DELIVERIES_SERVICE_URL
              value: "http://delivery-service"
            - name: NOTIFICATIONS_SERVICE_URL
              value: "http://notification-service"
            - name: NGINX_PORT
              value: "80"
            - name: FRONTEND_PORT
              value: "3205"
          ports:
            - containerPort: 3205
