apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: sabinghost19/quickbite-restaurant-service:v1.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 8081
